---
- name: Ensure lodestar group exists
  group:
    name: "{{ lodestar_group }}"
    state: present
  become: true
  register: lodestar_group_details

- name: Create lodestar user
  user:
    comment: lodestar client user
    name: "{{ lodestar_user }}"
    group: "{{ lodestar_group }}"
  become: true
  register: lodestar_user_details

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ lodestar_user }}"
    group: "{{ lodestar_group }}"
  loop:
    - "{{ lodestar_base_dir }}"
    - "{{ lodestar_config_dir }}"
    - "{{ lodestar_data_dir }}"
    - "{{ lodestar_log_dir }}"
  become: true

- name: Setup logrotate
  template:
    src: "logrotate/lodestar"
    dest: "/etc/logrotate.d/lodestar"
  become: true

- name: Stop lodestar
  community.docker.docker_compose:
    project_src: "{{ lodestar_base_dir }}"
    build: false
    stopped: true
    state: absent

- name: Create docker-compose.yml file
  template:
    src: lodestar-compose.yml.j2
    dest: "{{ lodestar_base_dir }}/docker-compose.yml"
    owner: "{{ lodestar_user }}"
    group: "{{ lodestar_group }}"
    mode: 0644
  become: yes

- name: Give access to docker.sock
  acl:
    path: /var/run/docker.sock
    entity: 1000
    etype: user
    permissions: rw
    state: present
  become: yes

- name: Restart services
  community.docker.docker_compose:
    project_src: "{{ lodestar_base_dir }}"
    build: false
    restarted: true
    state: present
