---
- name: Ensure we have sane configuration
  block:
    - fail:
        msg: You must set "lodestar_version" for this role to run
      when: lodestar_version is not defined

- name: Get IP address to bind to if not provided
  ansible.builtin.include_tasks: "network.yml"
  when: not lodestar_host_ip

- name: Install lodestar
  ansible.builtin.include_tasks: "install.yml"

- name: Set version info on a local file
  ansible.builtin.include_tasks: "tags.yml"
