- name: tags | Set the version on a local file so it can be used by other automation
  ansible.builtin.copy: 
    content: "{{ lodestar_version }}"
    dest: "{{ lodestar_version_info_file }}"
    owner: "{{ lodestar_user }}"
    group: "{{ lodestar_group }}"
    mode: 0644    
  become: true

- name: tags | Set the version for the validator so it can be used by other automation
  ansible.builtin.copy: 
    content: "{{ lodestar_version }}"
    dest: "{{ lodestar_validator_version_info_file }}"
    owner: "{{ lodestar_user }}"
    group: "{{ lodestar_group }}"
    mode: 0644   
  become: true
  when: lodestar_validator_enabled 